apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: burda
  name: burda
  namespace: burda-hackday
spec:
  replicas: 1
  selector:
    matchLabels:
      run: burda
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: burda
    spec:
      containers:
      - image: gcr.io/test-mg-1006/burda:murrayc-zeromq
        imagePullPolicy: IfNotPresent
        name: burda
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 5556
        - containerPort: 5557
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: burda
  namespace: burda-hackday
spec:
  ports:
  - port: 5556
    protocol: TCP
    name: pull
  - port: 5557
    protocol: TCP
    name: pub
  selector:
    run: burda
  type: LoadBalancer
